W0713 16:13:11.012000 1463101 site-packages/torch/distributed/run.py:766] 
W0713 16:13:11.012000 1463101 site-packages/torch/distributed/run.py:766] *****************************************
W0713 16:13:11.012000 1463101 site-packages/torch/distributed/run.py:766] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0713 16:13:11.012000 1463101 site-packages/torch/distributed/run.py:766] *****************************************
[W713 16:13:11.913718004 socket.cpp:755] [c10d] The client socket cannot be initialized to connect to [clara10.sc.uni-leipzig.de]:15285 (errno: 97 - Address family not supported by protocol).
[W713 16:13:11.138199515 socket.cpp:755] [c10d] The client socket cannot be initialized to connect to [clara10.sc.uni-leipzig.de]:44895 (errno: 97 - Address family not supported by protocol).
[W713 16:13:15.065425566 socket.cpp:755] [c10d] The client socket cannot be initialized to connect to [clara10.sc.uni-leipzig.de]:44895 (errno: 97 - Address family not supported by protocol).
[W713 16:13:15.065565216 socket.cpp:755] [c10d] The client socket cannot be initialized to connect to [clara10.sc.uni-leipzig.de]:44895 (errno: 97 - Address family not supported by protocol).
[W713 16:13:15.065669906 socket.cpp:755] [c10d] The client socket cannot be initialized to connect to [clara10.sc.uni-leipzig.de]:44895 (errno: 97 - Address family not supported by protocol).
[W713 16:13:15.065722106 socket.cpp:755] [c10d] The client socket cannot be initialized to connect to [clara10.sc.uni-leipzig.de]:44895 (errno: 97 - Address family not supported by protocol).
wandb: Currently logged in as: coyfelix7 (coyfelix7-universit-t-leipzig) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin
[rank3]: Traceback (most recent call last):
[rank3]:   File "/home/sc.uni-leipzig.de/ci72buri/projects/vae/Leipzig_big_data_praktikum_gene_expression_autoencoder/train_vae.py", line 162, in <module>
[rank3]:     train()
[rank3]:   File "/home/sc.uni-leipzig.de/ci72buri/projects/vae/Leipzig_big_data_praktikum_gene_expression_autoencoder/train_vae.py", line 91, in train
[rank3]:     dataset_tmp = SingleCellDataset(
[rank3]: NameError: name 'SingleCellDataset' is not defined
[rank2]: Traceback (most recent call last):
[rank2]:   File "/home/sc.uni-leipzig.de/ci72buri/projects/vae/Leipzig_big_data_praktikum_gene_expression_autoencoder/train_vae.py", line 162, in <module>
[rank2]:     train()
[rank2]:   File "/home/sc.uni-leipzig.de/ci72buri/projects/vae/Leipzig_big_data_praktikum_gene_expression_autoencoder/train_vae.py", line 91, in train
[rank2]:     dataset_tmp = SingleCellDataset(
[rank2]: NameError: name 'SingleCellDataset' is not defined
[rank1]: Traceback (most recent call last):
[rank1]:   File "/home/sc.uni-leipzig.de/ci72buri/projects/vae/Leipzig_big_data_praktikum_gene_expression_autoencoder/train_vae.py", line 162, in <module>
[rank1]:     train()
[rank1]:   File "/home/sc.uni-leipzig.de/ci72buri/projects/vae/Leipzig_big_data_praktikum_gene_expression_autoencoder/train_vae.py", line 91, in train
[rank1]:     dataset_tmp = SingleCellDataset(
[rank1]: NameError: name 'SingleCellDataset' is not defined
W0713 16:13:16.674000 1463101 site-packages/torch/distributed/elastic/multiprocessing/api.py:900] Sending process 1463125 closing signal SIGTERM
W0713 16:13:16.675000 1463101 site-packages/torch/distributed/elastic/multiprocessing/api.py:900] Sending process 1463127 closing signal SIGTERM
E0713 16:13:16.839000 1463101 site-packages/torch/distributed/elastic/multiprocessing/api.py:874] failed (exitcode: 1) local_rank: 1 (pid: 1463126) of binary: /home/sc.uni-leipzig.de/ci72buri/.conda/envs/cell-vae/bin/python3.10
Traceback (most recent call last):
  File "/home/sc.uni-leipzig.de/ci72buri/.conda/envs/cell-vae/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/sc.uni-leipzig.de/ci72buri/.conda/envs/cell-vae/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
  File "/home/sc.uni-leipzig.de/ci72buri/.conda/envs/cell-vae/lib/python3.10/site-packages/torch/distributed/run.py", line 892, in main
    run(args)
  File "/home/sc.uni-leipzig.de/ci72buri/.conda/envs/cell-vae/lib/python3.10/site-packages/torch/distributed/run.py", line 883, in run
    elastic_launch(
  File "/home/sc.uni-leipzig.de/ci72buri/.conda/envs/cell-vae/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 139, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/sc.uni-leipzig.de/ci72buri/.conda/envs/cell-vae/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 270, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train_vae.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2025-07-13_16:13:16
  host      : clara10.sc.uni-leipzig.de
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 1463128)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-07-13_16:13:16
  host      : clara10.sc.uni-leipzig.de
  rank      : 1 (local_rank: 1)
  exitcode  : 1 (pid: 1463126)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
