MASTER_ADDR is 172.18.62.11
PING 172.18.62.11 (172.18.62.11) 56(84) bytes of data.
64 bytes from 172.18.62.11: icmp_seq=1 ttl=64 time=0.044 ms

--- 172.18.62.11 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.044/0.044/0.044/0.000 ms
W0715 01:15:42.302000 66284 site-packages/torch/distributed/run.py:766] 
W0715 01:15:42.302000 66284 site-packages/torch/distributed/run.py:766] *****************************************
W0715 01:15:42.302000 66284 site-packages/torch/distributed/run.py:766] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
W0715 01:15:42.302000 66284 site-packages/torch/distributed/run.py:766] *****************************************
[W715 01:15:42.261822009 socket.cpp:755] [c10d] The client socket cannot be initialized to connect to [paula11.sc.uni-leipzig.de]:27886 (errno: 97 - Address family not supported by protocol).
[W715 01:15:42.420202462 socket.cpp:755] [c10d] The client socket cannot be initialized to connect to [paula11.sc.uni-leipzig.de]:43403 (errno: 97 - Address family not supported by protocol).
Traceback (most recent call last):
  File "/home/sc.uni-leipzig.de/ci72buri/projects/vae/Leipzig_big_data_praktikum_gene_expression_autoencoder/train_vae.py", line 18, in <module>
    from src.vae import CellVAE
  File "/home/sc.uni-leipzig.de/ci72buri/projects/vae/Leipzig_big_data_praktikum_gene_expression_autoencoder/src/vae.py", line 1, in <module>
    class CellVAE(nn.Module):
NameError: name 'nn' is not defined
Traceback (most recent call last):
  File "/home/sc.uni-leipzig.de/ci72buri/projects/vae/Leipzig_big_data_praktikum_gene_expression_autoencoder/train_vae.py", line 18, in <module>
    from src.vae import CellVAE
  File "/home/sc.uni-leipzig.de/ci72buri/projects/vae/Leipzig_big_data_praktikum_gene_expression_autoencoder/src/vae.py", line 1, in <module>
    class CellVAE(nn.Module):
NameError: name 'nn' is not defined
Traceback (most recent call last):
  File "/home/sc.uni-leipzig.de/ci72buri/projects/vae/Leipzig_big_data_praktikum_gene_expression_autoencoder/train_vae.py", line 18, in <module>
    from src.vae import CellVAE
  File "/home/sc.uni-leipzig.de/ci72buri/projects/vae/Leipzig_big_data_praktikum_gene_expression_autoencoder/src/vae.py", line 1, in <module>
    class CellVAE(nn.Module):
NameError: name 'nn' is not defined
Traceback (most recent call last):
  File "/home/sc.uni-leipzig.de/ci72buri/projects/vae/Leipzig_big_data_praktikum_gene_expression_autoencoder/train_vae.py", line 18, in <module>
    from src.vae import CellVAE
  File "/home/sc.uni-leipzig.de/ci72buri/projects/vae/Leipzig_big_data_praktikum_gene_expression_autoencoder/src/vae.py", line 1, in <module>
    class CellVAE(nn.Module):
NameError: name 'nn' is not defined
W0715 01:15:47.286000 66284 site-packages/torch/distributed/elastic/multiprocessing/api.py:900] Sending process 66313 closing signal SIGTERM
W0715 01:15:47.287000 66284 site-packages/torch/distributed/elastic/multiprocessing/api.py:900] Sending process 66314 closing signal SIGTERM
W0715 01:15:47.287000 66284 site-packages/torch/distributed/elastic/multiprocessing/api.py:900] Sending process 66315 closing signal SIGTERM
W0715 01:15:47.287000 66284 site-packages/torch/distributed/elastic/multiprocessing/api.py:900] Sending process 66316 closing signal SIGTERM
E0715 01:15:47.501000 66284 site-packages/torch/distributed/elastic/multiprocessing/api.py:874] failed (exitcode: 1) local_rank: 0 (pid: 66312) of binary: /home/sc.uni-leipzig.de/ci72buri/.conda/envs/cell-vae/bin/python3.10
Traceback (most recent call last):
  File "/home/sc.uni-leipzig.de/ci72buri/.conda/envs/cell-vae/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/sc.uni-leipzig.de/ci72buri/.conda/envs/cell-vae/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
  File "/home/sc.uni-leipzig.de/ci72buri/.conda/envs/cell-vae/lib/python3.10/site-packages/torch/distributed/run.py", line 892, in main
    run(args)
  File "/home/sc.uni-leipzig.de/ci72buri/.conda/envs/cell-vae/lib/python3.10/site-packages/torch/distributed/run.py", line 883, in run
    elastic_launch(
  File "/home/sc.uni-leipzig.de/ci72buri/.conda/envs/cell-vae/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 139, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/sc.uni-leipzig.de/ci72buri/.conda/envs/cell-vae/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 270, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
train_vae.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2025-07-15_01:15:47
  host      : paula11.sc.uni-leipzig.de
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 66312)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
